import { render, screen, waitFor } from "@testing-library/react"
import userEvent from "@testing-library/user-event"
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest"

import { FullSongWizardModal } from "@/components/song/full-song/FullSongWizardModal"
import { PlayerProvider } from "@/contexts/player-context"
import { makeClip } from "@/test/clip-factory"

vi.mock("@/hooks/use-auth", () => ({
  useAuth: () => ({ accessToken: "tok", isLoading: false, isAuthenticated: true }),
}))

const submitExtend = vi.fn()
vi.mock("@/lib/editing", () => ({
  submitExtend: (...args: unknown[]) => submitExtend(...args),
}))

const fetchJobStatus = vi.fn()
vi.mock("@/lib/job-status", () => ({
  fetchJobStatus: (...args: unknown[]) => fetchJobStatus(...args),
}))

let genCounter = 0

beforeEach(() => {
  genCounter = 0
  submitExtend.mockResolvedValue({ status: "accepted", jobId: "j", estimatedSeconds: 0 })
  // Each section's extend completes with a fresh clip id, so we can assert the
  // next extend continues from the previously accepted clip.
  fetchJobStatus.mockImplementation(() =>
    Promise.resolve({ kind: "completed", clipIds: [`gen-${++genCounter}`] })
  )
})

afterEach(() => vi.clearAllMocks())

function renderWizard(onClose = vi.fn()) {
  render(
    <PlayerProvider>
      <FullSongWizardModal
        clip={makeClip({ id: "seed", duration: 30, title: "Seed", style_tags: ["lofi"] })}
        open
        onClose={onClose}
      />
    </PlayerProvider>
  )
  return { onClose }
}

describe("FullSongWizardModal", () => {
  it("plans the structure, then generates the first section from the seed", async () => {
    renderWizard()
    // Planning step.
    expect(screen.getByText(/Planned structure/)).toBeInTheDocument()
    await userEvent.click(screen.getByRole("button", { name: /start generation/i }))

    // First section is generated by extending the seed clip.
    await screen.findByRole("button", { name: "Accept" })
    // "Section 1 of 7" shows in both the header and the review heading.
    expect(screen.getAllByText(/Section 1 of 7/).length).toBeGreaterThan(0)
    expect(submitExtend.mock.calls[0][0]).toBe("seed")
    expect(submitExtend.mock.calls[0][1].style_override).toMatch(/^lofi, intro/)
  })

  it("extends each accepted clip when advancing to the next section", async () => {
    renderWizard()
    await userEvent.click(screen.getByRole("button", { name: /start generation/i }))
    await userEvent.click(await screen.findByRole("button", { name: "Accept" }))

    // Section 2 continues from section 1's accepted clip (gen-1).
    await waitFor(() => expect(submitExtend).toHaveBeenCalledTimes(2))
    expect(submitExtend.mock.calls[1][0]).toBe("gen-1")
    expect((await screen.findAllByText(/Section 2 of 7/)).length).toBeGreaterThan(0)
  })

  it("regenerates a rejected section from the same clip with new instructions", async () => {
    renderWizard()
    await userEvent.click(screen.getByRole("button", { name: /start generation/i }))
    await screen.findByRole("button", { name: "Accept" })

    await userEvent.click(screen.getByRole("button", { name: "Reject" }))
    await userEvent.type(
      screen.getByLabelText(/what should change/i),
      "brighter"
    )
    await userEvent.click(screen.getByRole("button", { name: "Regenerate" }))

    await waitFor(() => expect(submitExtend).toHaveBeenCalledTimes(2))
    // Still extending the seed (nothing was accepted), now steered by the note.
    expect(submitExtend.mock.calls[1][0]).toBe("seed")
    expect(submitExtend.mock.calls[1][1].style_override).toMatch(/brighter$/)
  })

  it("completes once every section is accepted", async () => {
    renderWizard()
    await userEvent.click(screen.getByRole("button", { name: /start generation/i }))
    for (let i = 0; i < 7; i++) {
      await userEvent.click(await screen.findByRole("button", { name: "Accept" }))
    }
    expect(
      await screen.findByText(/saved to your workspace/i)
    ).toBeInTheDocument()
    expect(
      screen.getByRole("button", { name: /open in song detail/i })
    ).toBeInTheDocument()
    expect(submitExtend).toHaveBeenCalledTimes(7)
  })

  it("confirms before discarding an in-progress generation", async () => {
    // Hold the first section in the generating state (extend never resolves).
    submitExtend.mockReturnValue(new Promise(() => {}))
    const { onClose } = renderWizard()
    await userEvent.click(screen.getByRole("button", { name: /start generation/i }))
    await screen.findByText(/Generating intro/i)

    // Escape asks to confirm rather than closing outright.
    await userEvent.keyboard("{Escape}")
    expect(screen.getByText(/discard the full-song build/i)).toBeInTheDocument()
    expect(onClose).not.toHaveBeenCalled()

    await userEvent.click(screen.getByRole("button", { name: /keep going/i }))
    expect(screen.queryByText(/discard the full-song build/i)).not.toBeInTheDocument()

    await userEvent.keyboard("{Escape}")
    await userEvent.click(screen.getByRole("button", { name: "Discard" }))
    expect(onClose).toHaveBeenCalledOnce()
  })
})
